import type { Product } from './store'

export type { Product }

export type Category = {
  slug: string
  label: string
  count: number
}

export const categories: Category[] = [
  { slug: 'red-onion',   label: 'Dehydrated Red Onion',   count: 5 },
  { slug: 'white-onion', label: 'Dehydrated White Onion', count: 5 },
  { slug: 'pink-onion',  label: 'Dehydrated Pink Onion',  count: 5 },
  { slug: 'garlic',      label: 'Dehydrated Garlic',      count: 5 },
]

export const products: Product[] = [
  // RED ONION
  { id:'red-flakes',   category:'Dehydrated Red Onion',   categorySlug:'red-onion',   name:'Red Onion Flakes',   image:'/images/products/Red-Onion-Flakes.jpg',              description:'Crisp, uniform flakes ideal for soups, seasonings and ready meals.',                             fullDescription:'Our Dehydrated Red Onion Flakes are produced from premium quality red onions sourced directly from certified farmers. Cleaned, peeled, sliced, and dehydrated under controlled temperature conditions to preserve maximum flavour, colour, and nutritional value.',                                                                              specs:{ Form:'Flakes',        Colour:'Deep reddish-brown', Moisture:'Max 5%', Usage:'Soups, Seasonings, Ready Meals',  Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'red-chopped',  category:'Dehydrated Red Onion',   categorySlug:'red-onion',   name:'Red Onion Chopped',  image:'/images/products/Red_Onion_Chopped.jpeg',             description:'Precisely chopped for bulk food manufacturing and HoReCa applications.',                          fullDescription:'Dehydrated Red Onion Chopped is manufactured using the finest red onions, carefully cleaned and chopped to uniform size before dehydration. Ideal for bulk food manufacturing units, HoReCa businesses, and food processing industries.',                                                                                                        specs:{ Form:'Chopped / Diced', Colour:'Reddish-brown',     Moisture:'Max 5%', Usage:'Food Manufacturing, HoReCa',    Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'red-minced',   category:'Dehydrated Red Onion',   categorySlug:'red-onion',   name:'Red Onion Minced',   image:'/images/products/RED_ONION_MINCED.png',               description:'Fine minced red onion — ideal for sauces, spice blends and condiments.',                          fullDescription:'Red Onion Minced delivers intense onion flavour in sauces, spice blends, marinades, and condiment manufacturing. The dehydration process ensures full flavour retention without any additives or preservatives.',                                                                                                                                 specs:{ Form:'Minced',        Colour:'Reddish-brown',     Moisture:'Max 5%', Usage:'Sauces, Spice Blends, Condiments', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'red-powder',   category:'Dehydrated Red Onion',   categorySlug:'red-onion',   name:'Red Onion Powder',   image:'/images/products/red-onion-powder-500x500.webp',      description:'Fine-ground powder with intense flavour for seasoning mixes and marinades.',                        fullDescription:'Fine-ground from premium dehydrated red onions. Provides intense, consistent flavour and is used extensively in seasoning mixes, instant soups, gravies, marinades, and snack coatings.',                                                                                                                                                        specs:{ Form:'Fine Powder',   Colour:'Light reddish-brown', Moisture:'Max 5%', Usage:'Seasoning, Gravies, Marinades', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'red-granules', category:'Dehydrated Red Onion',   categorySlug:'red-onion',   name:'Red Onion Granules', image:'/images/products/Red_Onion_Granules.webp',             description:'Consistent granules with strong aroma — ideal for snack and spice producers.',                     fullDescription:'Medium particle size providing strong aroma and flavour. Widely used in snack seasonings, dry spice blends, ready-to-cook mixes, and condiment manufacturing.',                                                                                                                                                                                 specs:{ Form:'Granules',      Colour:'Reddish-brown',     Moisture:'Max 5%', Usage:'Snacks, Spice Blends, RTC Mixes', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  // WHITE ONION
  { id:'white-flakes',   category:'Dehydrated White Onion', categorySlug:'white-onion', name:'White Onion Flakes',   image:'/images/products/White_Onion_Flakes.jpg',          description:'Premium light-coloured flakes with mild flavour for food processing.',                             fullDescription:'Premium Dehydrated White Onion Flakes offer a mild, clean flavour with excellent colour retention. Ideal for international food manufacturers requiring a consistent, light-coloured ingredient.',                                                                                                                                              specs:{ Form:'Flakes',        Colour:'Cream / Off-white', Moisture:'Max 5%', Usage:'Soups, Seasonings, Food Processing', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'white-chopped',  category:'Dehydrated White Onion', categorySlug:'white-onion', name:'White Onion Chopped',  image:'/images/products/White_Onion_Chopped.jpg',          description:'Uniformly chopped — easy to reconstitute with long shelf life.',                                  fullDescription:'Uniformly chopped dehydrated white onion with easy reconstitution and long shelf life. Clean, neutral flavour profile that complements a broad range of food applications.',                                                                                                                                                                    specs:{ Form:'Chopped / Diced', Colour:'Cream / Off-white', Moisture:'Max 5%', Usage:'Food Manufacturing, Catering',  Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'white-minced',   category:'Dehydrated White Onion', categorySlug:'white-onion', name:'White Onion Minced',   image:'/images/products/White_Onion_Minced.jpg',           description:'Finely minced — ideal for ready-to-cook blends and seasoning manufacturers.',                       fullDescription:'Finely minced white onion with superior consistency, ideal for ready-to-cook blends, seasoning powder manufacturers, and processed food units.',                                                                                                                                                                                                specs:{ Form:'Minced',        Colour:'Cream / Off-white', Moisture:'Max 5%', Usage:'RTC Blends, Seasonings',          Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'white-granules', category:'Dehydrated White Onion', categorySlug:'white-onion', name:'White Onion Granules', image:'/images/products/White_Onion_Granules.jpg',         description:'Granulated with clean consistent size — perfect for bulk food manufacturing.',                      fullDescription:'Granulated dehydrated white onion with clean, consistent particle size. Perfect for bulk food manufacturing, seasoning producers, and food ingredient distributors globally.',                                                                                                                                                                  specs:{ Form:'Granules',      Colour:'Cream / Off-white', Moisture:'Max 5%', Usage:'Bulk Manufacturing, Seasonings',   Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'white-powder',   category:'Dehydrated White Onion', categorySlug:'white-onion', name:'White Onion Powder',   image:'/images/products/White_Onion_Powder.jpg',           description:'Ultra-fine powder with high pungency and superior flavour retention.',                              fullDescription:'Ultra-fine dehydrated white onion powder with high pungency, excellent solubility, and long-lasting flavour. Preferred by international food manufacturers for soups, sauces, and gravies.',                                                                                                                                                    specs:{ Form:'Fine Powder',   Colour:'Off-white',         Moisture:'Max 5%', Usage:'Soups, Sauces, Gravies, Snacks',  Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  // PINK ONION
  { id:'pink-flakes',   category:'Dehydrated Pink Onion',  categorySlug:'pink-onion',  name:'Pink Onion Flakes',   image:'/images/products/Pink_Onion_Flakes.webp',             description:'Distinctive flakes with unique colour profile for premium product lines.',                         fullDescription:'Distinctive dehydrated pink onion flakes with a unique colour profile and characteristic flavour, sought after for premium and specialty food product lines.',                                                                                                                                                                                  specs:{ Form:'Flakes',        Colour:'Light pink / Rose', Moisture:'Max 5%', Usage:'Gourmet Foods, Specialty Products', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'pink-chopped',  category:'Dehydrated Pink Onion',  categorySlug:'pink-onion',  name:'Pink Onion Chopped',  image:'/images/products/dehydrated-chopped-pink-onion.jpg',  description:'Aromatic chopped pink onion suited for speciality food applications.',                              fullDescription:'Aromatic chopped dehydrated pink onion suited for specialty food applications, ethnic cuisine manufacturers, and premium seasoning producers.',                                                                                                                                                                                                  specs:{ Form:'Chopped',       Colour:'Light pink / Rose', Moisture:'Max 5%', Usage:'Specialty Foods, Ethnic Cuisine',  Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'pink-minced',   category:'Dehydrated Pink Onion',  categorySlug:'pink-onion',  name:'Pink Onion Minced',   image:'/images/products/Pink_Onion_Minced.jpg',               description:'Minced with robust flavour — used in gourmet food preparations worldwide.',                          fullDescription:'Finely minced pink onion with a robust, distinctive flavour, used in gourmet food preparations, premium sauces, and specialty spice blends worldwide.',                                                                                                                                                                                         specs:{ Form:'Minced',        Colour:'Light pink',        Moisture:'Max 5%', Usage:'Gourmet Foods, Sauces',            Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'pink-granules', category:'Dehydrated Pink Onion',  categorySlug:'pink-onion',  name:'Pink Onion Granules', image:'/images/products/Pink_Onion_Granules.jpg',             description:'Granulated pink onion with consistent size for seasoning blends and spice mixes.',                  fullDescription:'Granulated dehydrated pink onion with consistent particle size and characteristic pink colour. Used in specialty seasoning blends, flavoured snacks, and ethnic spice mixes across international markets.',                                                                                                                                      specs:{ Form:'Granules',      Colour:'Light pink',        Moisture:'Max 5%', Usage:'Seasoning Blends, Spice Mixes',    Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'pink-powder',   category:'Dehydrated Pink Onion',  categorySlug:'pink-onion',  name:'Pink Onion Powder',   image:'/images/products/Pink_Onion_Powder.webp',              description:'Rich natural flavour powder — ideal for ethnic spice mixes and marinades.',                          fullDescription:'Rich natural flavour pink onion powder, ideal for ethnic spice mixes, marinade producers, and specialty food manufacturers. Retains characteristic flavour through precision dehydration.',                                                                                                                                                     specs:{ Form:'Fine Powder',   Colour:'Light pink',        Moisture:'Max 5%', Usage:'Ethnic Spices, Marinades',         Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  // GARLIC
  { id:'garlic-flakes',   category:'Dehydrated Garlic', categorySlug:'garlic', name:'Garlic Flakes',   image:'/images/products/Garlic_Flakes.jpg',   description:'Pure dehydrated flakes with strong aroma — popular in European and Middle Eastern markets.', fullDescription:'Pure dehydrated garlic flakes from premium quality garlic bulbs. Strong, authentic aroma popular in European, Middle Eastern, and Asian food markets. 100% natural, no additives.',                      specs:{ Form:'Flakes',      Colour:'Creamy white',   Moisture:'Max 5%', Usage:'Soups, Sauces, Seasonings',        Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'garlic-chopped',  category:'Dehydrated Garlic', categorySlug:'garlic', name:'Garlic Chopped',  image:'/images/products/Garlic_Chopped.webp',  description:'Uniform chopped garlic — ideal for large-scale food production and HoReCa.',                fullDescription:'Uniformly chopped dehydrated garlic, ideal for large-scale food production, HoReCa, and food service industries. Consistent flavour delivery with easy measurement and handling.',                            specs:{ Form:'Chopped / Diced', Colour:'Creamy white', Moisture:'Max 5%', Usage:'Food Manufacturing, HoReCa',    Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'garlic-minced',   category:'Dehydrated Garlic', categorySlug:'garlic', name:'Garlic Minced',   image:'/images/products/Garlic_Minced.jpg',   description:'Finely minced with high pungency — for sauce producers and condiment manufacturers.',       fullDescription:'Finely minced dehydrated garlic with intense pungency, preferred by sauce producers, condiment manufacturers, and ready-meal processors for concentrated flavour.',                                            specs:{ Form:'Minced',      Colour:'Creamy white',   Moisture:'Max 5%', Usage:'Sauces, Condiments, Ready Meals', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'garlic-granules', category:'Dehydrated Garlic', categorySlug:'garlic', name:'Garlic Granules', image:'/images/products/Garlic_Granules.jpg', description:'Consistent granules — widely used in spice blends, snack seasonings and marinades.',       fullDescription:'Consistent-sized dehydrated garlic granules, widely preferred in spice blends, snack seasonings, dry rub marinades, and baked goods.',                                                                          specs:{ Form:'Granules',    Colour:'Creamy white',   Moisture:'Max 5%', Usage:'Spice Blends, Snacks, Marinades',  Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
  { id:'garlic-powder',   category:'Dehydrated Garlic', categorySlug:'garlic', name:'Garlic Powder',   image:'/images/products/Garlic_Powder.webp',  description:'Premium quality powder with superior solubility and consistent flavour.',                  fullDescription:'Premium quality dehydrated garlic powder with superior solubility, consistent flavour, and long shelf life. A staple ingredient for the global food industry.',                                                 specs:{ Form:'Fine Powder', Colour:'Off-white / Cream', Moisture:'Max 5%', Usage:'Seasoning, Instant Products, Sauces', Shelf:'36 Months', Packing:'10 Kg / 25 Kg Bags' } },
]
